version: "3.8"

name: research-dispatcher

services:
  system:
    hostname: dev
    container_name: research-dispatcher-dev
    build:
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
      - home:/home/node
    networks:
      - back-tier
      - front-tier

  public-web:
    container_name: public-web
    extends:
      file: docker-compose.base.yml
      service: node-app-base
    command: npx nx run @sektek/public-web:start:dev
    networks:
      - back-tier
      - front-tier

  dispatcher:
    container_name: dispatcher
    depends_on:
      - rabbitmq
    extends:
      file: docker-compose.base.yml
      service: node-app-base
    command: npx nx run @sektek/dispatcher:start:dev
    networks:
      - back-tier

  ping-listener:
    container_name: ping-listener
    depends_on:
      - rabbitmq
    extends:
      file: docker-compose.base.yml
      service: node-app-base
    command: npx nx run @sektek/ping-listener:start:dev
    networks:
      - back-tier

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dispatcher-mq
    ports:
      - "15672:15672"
    networks:
      - back-tier

  redis:
    image: redis:7.2
    container_name: dispatcher-redis
    volumes:
      - redis:/data
    networks:
      - back-tier

volumes:
  home: {}
  redis: {}

networks:
  back-tier: {}
  front-tier: {}
