version: '3.8'

services:
  node-app-base:
    image: node:20
    restart: always
    working_dir: /app
    environment:
      - DEV_PLATFORM=node
      - OLTP_TRACE_EXPORTER_URL=http://agent:4318/v1/traces
    volumes:
      - ../..:/workspaces:cached
      - ../:/app
