version: "3.8"

name: research-dispatcher

services:
  system:
    hostname: dev
    container_name: research-dispatcher-dev
    build:
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    networks:
      - back-tier
      - front-tier

  # public-web:
  #   container_name: public-web
  #   extends:
  #     file: docker-compose.base.yml
  #     service: node-app-base
  #   command: npx nx run @sektek/public-web:start:dev
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - back-tier
  #     - front-tier

  # dispatcher:
  #   container_name: dispatcher
  #   extends:
  #     file: docker-compose.base.yml
  #     service: node-app-base
  #   command: npx nx run @sektek/dispatcher:start:dev
  #   networks:
  #     - back-tier

  # ping-listener:
  #   container_name: ping-listener
  #   extends:
  #     file: docker-compose.base.yml
  #     service: node-app-base
  #   command: npx nx run @sektek/ping-listener:start:dev

  rabbitmq:
    image: rabbitmq:3.12
    container_name: dispatcher-mq
    networks:
      - back-tier

  redis:
    image: redis:7.2
    container_name: dispatcher-redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - back-tier

volumes:
  redis: {}

networks:
  back-tier: {}
  front-tier: {}
