apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    editable: true
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          matcherType: label
          matcherRegex: trace_id
        - name: SpanID
          type: label
          matcherRegex: span_id
  - name: Tempo
    type: tempo
    access: proxy
    editable: true
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: Loki
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        filterByTraceID: true
        filterBySpanID: true

